name: First action
run-name: Yabba dabba doo ${{ github.actor }}
on: push
permissions:
  contents: write
jobs:
  add-file-lol-lol-lalglglaha-ha-g:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create file
        run: date > amazing.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Urgh...... GitHub